version: '3'
services:
  myapp:
    build: .
    ports:
      - "9898:9898"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
    networks:
      - macvlan_network
    restart: unless-stopped

networks:
  macvlan_network:
    external:
      name: macvlan_network
